version: "3"

services:
  caddy:
    image: caddy:2.4.6-alpine
    container_name: webserver
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
  graphdb:
    container_name: graphdb
    image: khaller/graphdb-free:1.3.5-graphdb9.11.2
    restart: always
    environment: 
      GDB_JAVA_OPTS: 
        -Xmx12g -Xms12g
    ports: 
      - 7200:7200
    volumes:
      - ./gdb/data:/opt/graphdb/data
      - ./gdb/import:/root/graphdb-import
      - ./gdb/work:/opt/graphdb/work
      - ./gdb/conf:/opt/graphdb/conf
      - ./gdb/log:/opt/graphdb/log
