version: "3"

services:
  graphdb:
    container_name: graphdb
    image: khaller/graphdb-free:1.3.5-graphdb9.11.2
    restart: always
    environment: 
      - GDB_HEAP_SIZE=12G
    ports: 
      - 7200:7200
    volumes:
      - ./gdb-data:/opt/graphdb/data
